# Generated by Django 5.0.6 on 2024-07-22 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_conversation_participants_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='sender',
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owned_conversations', to='base.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='users',
            field=models.ManyToManyField(related_name='conversations', to='base.user'),
        ),
    ]
