# Generated by Django 5.0.6 on 2024-07-28 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_created_at_conversation_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
